# Este é um fluxo de trabalho básico para ajudar você a começar com ações

name: CI

# Controla quando o fluxo de trabalho será executado
on:
  push:
    branches: [ "principal" ]
  pull_request:
    branches: [ "principal" ]
  workflow_dispatch:

# Uma execução de fluxo de trabalho é composta de um ou mais trabalhos
jobs:
  build:
    # O tipo de executor no qual o trabalho será executado
    runs-on: ubuntu-latest

    # As etapas representam uma sequência de tarefas
    steps:
      # Faz check-out do seu repositório
      - uses: actions/checkout@v3

      # Executa um único comando
      - name: Executa um script de uma linha
        run: echo "Olá, mundo!"

      # Executa um script multi-linha
      - name: Executa um script multi-linha
        run: |
          echo "Adicionar outras ações para construir,"
          echo "testar e implantar seu projeto."
